spring.application.name=hospitalManagement
server.port=5651

#DB configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/hospitalDB
spring.datasource.username=postgres
spring.datasource.password=root

server.servlet.context-path=/api/v1

spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.format_sql=false

#spring.jpa.defer-datasource-initialization=true
#spring.sql.init.mode=always
#spring.sql.init.data-locations=classpath:data.sql

#spring.security.user.name=joe
#spring.security.user.password=pass

jwt.secret.key=wK7mL0kqV8gP3N6cT1yZbR9fD2hJxQ4uE7sM5aB8cD0=